### ISSUE TITLE
Embed breaks content

### ISSUE THREAD

**Issue by nickdima** [jpuri/draftjs-to-html#12]
It seems that if you have an embed in the content it drops everything following it.
Looking at the DOM there isn't anything else following the iframe created for the embed.
Loading the same content in the editor it shows up correctly.

**Comment by jpuri** [comment]
Hey @nickdima: The generated output looks good here: https://jpuri.github.io/react-draft-wysiwyg/#/demo.

What is exactly issue you are facing ?

**Comment by jpuri** [comment]
Oh I see its issue cos of this parameter: `allowFullScreen` I will remove it soon.

Thanks for reporting.

**Comment by nickdima** [comment]
The problem is not in the editor but when you convert the article to html with `draftjs-to-html`

**Comment by jpuri** [comment]
Yep I saw its issue in generated html.

**Comment by nickdima** [comment]
Any idea on how to fix this?

**Comment by jpuri** [comment]
Hey @nickdima : Sorry for the delay, I am doing some fixes in editor today I will try to fix this also. You should have a new release of `draftjs-to-html` with fix by tomorrow.

**Comment by jpuri** [comment]
Hi @nickdima : `draftjs-to-html@0.7.1` should fix the issue.

**Comment by nickdima** [comment]
Thanks @jpuri but unfortunately that fix doesn't solve the issue. The content still gets cut bellow the iframe.
I'l try to explain better what's happening.

So in my `react-draft-wysiwyg` editor I have this article that contains a paragraph, an iframe embed and then another paragraph. But when I load this article with `draftjs-to-html` it has only the first paragraph and the iframe. So any content following the iframe it doesn't get converted.
Check the attached screenshots:

Editor:

<img width="801" alt="screen shot 2017-04-09 at 12 09 38" src="https://cloud.githubusercontent.com/assets/614468/24836487/7a836e02-1d1d-11e7-86e9-35397f9eaddc.png">

<hr/>

HTML (check the div container bellow and you'll see the last paragraph missing)

<img width="862" alt="screen shot 2017-04-09 at 12 04 25" src="https://cloud.githubusercontent.com/assets/614468/24836489/840bf746-1d1d-11e7-968b-8f731bc250e7.png">

**Comment by jpuri** [comment]
Oh ok, looks like I did not correctly understood it before - I will look into it again now.

**Comment by nickdima** [comment]
Thanks @jpuri !

**Comment by nickdima** [comment]
I submitted a PR that fixes this: #14
